/**
 * Gestión del inventario de códigos de bonos pre-cargados.
 *
 * Flujo de asignación:
 *  1. Al comprar se busca un código AVAILABLE del mismo importe en el inventario.
 *  2. Si no hay stock, se genera uno automáticamente (autoGenerated = true).
 *  3. En ambos casos el código pasa a PENDING_PAYMENT mientras Redsys procesa.
 *  4. Si el pago falla:
 *     – Código de inventario → vuelve a AVAILABLE.
 *     – Código auto-generado → se elimina (no era inventario, no tiene sentido conservarlo).
 */

import { prisma } from "@/lib/prisma";
import type { GiftCard } from "@prisma/client";

const INVENTORY_PLACEHOLDER = {
  purchaserName: "INVENTARIO",
  purchaserEmail: "inventario@gunnen.local",
  recipientEmail: "inventario@gunnen.local",
};

// Caracteres sin ambigüedad (sin I, O, 0, 1)
const CODE_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

function randomSegment(len: number): string {
  return Array.from(
    { length: len },
    () => CODE_CHARS[Math.floor(Math.random() * CODE_CHARS.length)]
  ).join("");
}

/** Genera un código único con formato GUNNEN-XXXX-XXXX, verificado contra la BD. */
async function generateUniqueCode(): Promise<string> {
  for (let attempt = 0; attempt < 30; attempt++) {
    const code = `GUNNEN-${randomSegment(4)}-${randomSegment(4)}`;
    const existing = await prisma.giftCard.findUnique({ where: { code } });
    if (!existing) return code;
  }
  // Fallback con timestamp para garantizar unicidad
  return `GUNNEN-${randomSegment(4)}-${Date.now().toString(36).toUpperCase().slice(-4)}`;
}

export interface ClaimGiftCardData {
  amount: number;
  pricePerPerson?: number;
  numberOfPeople?: number;
  menuName?: string;
  purchaserName: string;
  purchaserEmail: string;
  recipientName?: string;
  recipientEmail: string;
  message?: string;
  sendDate: Date;
  expiresAt: Date;
  redsysOrder: string;
}

/**
 * Intenta reservar un código AVAILABLE del inventario.
 * Si no hay stock para ese importe, genera uno automáticamente.
 */
export async function claimAvailableGiftCard(
  data: ClaimGiftCardData
): Promise<GiftCard | null> {
  // ── 1. Intentar asignar desde inventario ─────────────────────────────────
  const candidates = await prisma.giftCard.findMany({
    where: { status: "AVAILABLE", amount: data.amount },
    select: { id: true },
  });

  const shuffled = [...candidates].sort(() => Math.random() - 0.5);

  for (const { id } of shuffled) {
    const updated = await prisma.giftCard.updateMany({
      where: { id, status: "AVAILABLE" },
      data: {
        status: "PENDING_PAYMENT",
        menuName: data.menuName || null,
        numberOfPeople: data.numberOfPeople || 1,
        purchaserName: data.purchaserName,
        purchaserEmail: data.purchaserEmail,
        recipientName: data.recipientName || null,
        recipientEmail: data.recipientEmail,
        message: data.message || null,
        sendDate: data.sendDate,
        expiresAt: data.expiresAt,
        remainingAmount: data.amount,
        stripePaymentIntentId: data.redsysOrder,
      },
    });

    if (updated.count === 1) {
      return prisma.giftCard.findUnique({ where: { id } });
    }
  }

  // ── 2. Sin stock → generar código automático ──────────────────────────────
  const code = await generateUniqueCode();

  return prisma.giftCard.create({
    data: {
      code,
      amount: data.amount,
      remainingAmount: data.amount,
      status: "PENDING_PAYMENT",
      menuName: data.menuName || null,
      numberOfPeople: data.numberOfPeople || 1,
      purchaserName: data.purchaserName,
      purchaserEmail: data.purchaserEmail,
      recipientName: data.recipientName || null,
      recipientEmail: data.recipientEmail,
      message: data.message || null,
      sendDate: data.sendDate,
      expiresAt: data.expiresAt,
      stripePaymentIntentId: data.redsysOrder,
      autoGenerated: true,
    },
  });
}

/**
 * Devuelve un bono al estado correcto si el pago falla:
 * – Si era de inventario → vuelve a AVAILABLE.
 * – Si fue auto-generado → se elimina.
 */
export async function releaseGiftCardToPool(giftCardId: string): Promise<void> {
  const card = await prisma.giftCard.findUnique({ where: { id: giftCardId } });
  if (!card) return;

  if (card.autoGenerated) {
    await prisma.giftCard.delete({ where: { id: giftCardId } });
  } else {
    await prisma.giftCard.update({
      where: { id: giftCardId },
      data: {
        status: "AVAILABLE",
        ...INVENTORY_PLACEHOLDER,
        recipientName: null,
        message: null,
        menuName: null,
        stripePaymentIntentId: null,
        paidAt: null,
      },
    });
  }
}

/** Crea un código de inventario (sin comprador). */
export function inventoryDefaults(amount: number, code: string, menuName?: string) {
  const expiresAt = new Date();
  expiresAt.setMonth(expiresAt.getMonth() + 6);

  return {
    code: code.toUpperCase(),
    amount,
    remainingAmount: amount,
    status: "AVAILABLE" as const,
    menuName: menuName || null,
    ...INVENTORY_PLACEHOLDER,
    recipientName: null,
    message: null,
    sendDate: new Date(),
    expiresAt,
    autoGenerated: false,
  };
}

export { INVENTORY_PLACEHOLDER };
